spring:
  application:
    name: twelve-factor
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  profiles: local
info:
  application:
    name: ${spring.application.name}
    platform: ${os.name}
---
spring:
  profiles: cloud
  datasource:
    url: ${vcap.services.twelve-factor-db.credentials.jdbc-url}
info:
  application:
    name: ${vcap.application.name}
    platform: ${platform.name}
