spring:
  application:
    name: twelve-factor
  jpa:
    open-in-view: false
  flyway:
    enabled: false
---
spring:
  profiles: local
info:
  application:
    name: ${spring.application.name}
    platform: ${os.name}
---
spring:
  profiles: cloud
info:
  application:
    name: ${vcap.application.name}
    platform: ${platform.name}