spring:
  application:
    name: twelve-factor
  jpa:
    open-in-view: false
  flyway:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: health,info
info:
  application:
    os: ${os.name}

---
spring:
  config:
    activate:
      on-profile: local
info:
  application:
    platform: Local Machine
    space: local-development
---
spring:
  config:
    activate:
      on-profile: heroku
  jpa:
    hibernate:
      ddl-auto: update
info:
  application:
    platform: Heroku
    space: ${space.name}