spring:
  application:
    name: twelve-factor
  jpa:
    open-in-view: false
  flyway:
    enabled: false
---
spring:
  profiles: local
info:
  application:
    environment: development
    platform: ${os.name}
---
spring:
  profiles: cloud
info:
  application:
    environment: ${vcap.application.space_name}
    platform: ${platform.name}