spring:
  application:
    name: twelve-factor
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/database?user=root&password=root-password
info:
  application:
    name: ${spring.application.name}
    platform: ${os.name}
---
spring:
  profiles: cloud
  datasource:
    url: ${vcap.services.twelve-factor-db.credentials.jdbc-url}
info:
  application:
    name: ${vcap.application.name}
    platform: ${platform.name}