spring:
  application:
    name: twelve-factor
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/database?user=user&password=password
info:
  application:
    environment: local
    platform: ${os.name}
---
spring:
  profiles: cloud
  datasource:
    url: ${vcap.services.twelve-factor-db.credentials.jdbc-url}
info:
  application:
    environment: ${vcap.application.space_name}
    platform: ${platform.name}