server:
  shutdown: graceful
spring:
  application:
    name: twelve-factor
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
info:
  application:
    os: ${os.name}
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
info:
  application:
    platform: Local Machine
    space: local-development
---
spring:
  config:
    activate:
      on-profile: heroku
info:
  application:
    platform: Heroku
    space: ${space.name}